config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  root 'pages#home'
  get  'pages/rooms'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImagesUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  def rooms
    @rooms = current_user.rooms
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id = current_user.id if current_user
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:price, :description, :title, :user_id, :capacity, :pets, :smoking, :wifi, :bathrooms, :bath, :parties, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coderbnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/pages/rooms.html.erb
<div class="container">
  <h1 class="title is-2">Rooms</h1>

  <table>
    <thead>
      <tr>
        <th>Price</th>
        <th>Description</th>
        <th>Title</th>
        <th>User</th>
        <th>Capacity</th>
        <th>Pets</th>
        <th>Smoking</th>
        <th>Wifi</th>
        <th>Bathrooms</th>
        <th>Bath</th>
        <th>Parties</th>
        <th>Photo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% current_user.rooms.each do |room| %>
        <tr>
          <td><%= room.price %></td>
          <td><%= room.description %></td>
          <td><%= room.title %></td>
          <td><%= room.user.email %></td>
          <td><%= room.capacity %></td>
          <td><%= room.pets %></td>
          <td><%= room.smoking %></td>
          <td><%= room.wifi %></td>
          <td><%= room.bathrooms %></td>
          <td><%= room.bath %></td>
          <td><%= room.parties %></td>
          <td><%= image_tag room.image.url if room.image? %></td>
          <td><%= link_to 'Show', room %></td>
          <td><%= link_to 'Edit', edit_room_path(room) %></td>
          <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/partials/_nav.html.erb
<nav class="nav has-shadow">
  <div class="container">
  <div class="nav-left">
    <a class="nav-item">
      <span class="title is-3">Coderbnb</span>
    </a>
  </div>

  <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
  <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
  <span class="nav-toggle">
    <span></span>
    <span></span>
    <span></span>
  </span>

  <!-- This "nav-menu" is hidden on mobile -->
  <!-- Add the modifier "is-active" to display it on mobile -->
  <div class="nav-right nav-menu">

    <span class="nav-item">
     <% if user_signed_in? %>
      <%= image_tag(Gravatar.new(current_user.email).image_url, size: "30")%>
      <span class="nav-item"><%= link_to('New Room For Rent', new_room_path, class:'button is-primary') %></span>
      <span class="nav-item"><%= link_to('Logout', destroy_user_session_path, :method => :delete, class:'button is-primary') %></span>
     <% else%>
      <span class="nav-item"><%= link_to('Sign up', new_user_registration_path, class:'button is-primary') %></span>
    </span>
    <% end %>
  </div>
  </div>
</nav>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>

  <div class="field">
    <%= f.label :pets %>
    <%= f.check_box :pets %>
  </div>

  <div class="field">
    <%= f.label :smoking %>
    <%= f.check_box :smoking %>
  </div>

  <div class="field">
    <%= f.label :wifi %>
    <%= f.check_box :wifi %>
  </div>

  <div class="field">
    <%= f.label :bathrooms %>
    <%= f.number_field :bathrooms %>
  </div>

  <div class="field">
    <%= f.label :bath %>
    <%= f.check_box :bath %>
  </div>

  <div class="field">
    <%= f.label :parties %>
    <%= f.check_box :parties %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Description</th>
      <th>Title</th>
      <th>User</th>
      <th>Capacity</th>
      <th>Pets</th>
      <th>Smoking</th>
      <th>Wifi</th>
      <th>Bathrooms</th>
      <th>Bath</th>
      <th>Parties</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.price %></td>
        <td><%= room.description %></td>
        <td><%= room.title %></td>
        <td><%= room.user %></td>
        <td><%= room.capacity %></td>
        <td><%= room.pets %></td>
        <td><%= room.smoking %></td>
        <td><%= room.wifi %></td>
        <td><%= room.bathrooms %></td>
        <td><%= room.bath %></td>
        <td><%= room.parties %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>
</div>

app/views/rooms/new.html.erb
<div class="container">
<h1 class="title is-2">New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Title:</strong>
  <%= @room.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @room.user %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @room.pets %>
</p>

<p>
  <strong>Smoking:</strong>
  <%= @room.smoking %>
</p>

<p>
  <strong>Wifi:</strong>
  <%= @room.wifi %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @room.bathrooms %>
</p>

<p>
  <strong>Bath:</strong>
  <%= @room.bath %>
</p>

<p>
  <strong>Parties:</strong>
  <%= @room.parties %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>
</div>